[package]
name = "sdl-host"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-plugin-host = { path = "../.." }
sdl2 = "0.36.0"
winapi = { version = "0.3.9", features = ["windef"] }
objc2-app-kit = "0.3.1"
